# Default values for hl-explorer.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: hypersasha/hl-explorer
  tag: 0.3.7
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # certmanager.k8s.io/cluster-issuer: "letsencrypt-staging"
  path: /
  hosts: []
  #  - hl-explorer.local
  tls: []
  #  - secretName: hl-explorer-tls
  #    hosts:
  #      - hl-explorer.local

## Settings used in configMap "--db"
db:
  # Must be created using this command:
  # psql -h localhost -p 5432 -U $USER -v dbname=$DATABASE -v user=$USER -v passwd=$PASSWD -f ./explorerpg.sql
  chart: hle-pg-postgresql
  database: hl_explorer

secrets:
  # We need a secret for the Organisation certificate and key
  peerAdminCert: hlf--peer-admincert
  peerAdminKey: hlf--peer-adminkey
  ordAdminCert: hlf--ord-admincert
  ordAdminKey: hlf--ord-adminkey
  hlbConnection: hl--explorer-connection
  caServerTls: ica-peer--tls

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
